# Generated by Django 4.2.6 on 2023-10-12 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitmentCount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "count",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(7)]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealCommitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=255, null=True)),
                ("cost", models.FloatField(blank=True, default=0)),
                ("achieved", models.DateTimeField(blank=True, null=True)),
                ("activated", models.BooleanField(default=False)),
                (
                    "commitment_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commitment.commitmentcount",
                    ),
                ),
            ],
        ),
    ]
